Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5110)
('train_imgs: ', (12, 3, 1661, 2325))
imgs_std:
32.7681903164
imgs_mean:
47.403771015
imgs:
(12, 3, 1661, 2325)
Passed!
('imgs.shape: ', (12, 3, 1661, 2325))
('imgs_equalized.shape: ', (12, 3, 1661, 2325))

train images/masks shape:
(12, 3, 1329, 2325)
train images range (min-max): 0.0 - 1.0
train masks are within 0-1

patches per full image: 1000

train PATCHES images/masks shape:
(12000, 3, 64, 64)
train PATCHES images range (min-max): 0.0 - 1.0
./src/retinaNN_training.py:121: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Elemwise{t..., inputs=/input_1)`
  model = Model(input=inputs, output=conv7)
Traceback (most recent call last):
  File "./src/retinaNN_training.py", line 227, in <module>
    model = get_unet(n_ch, patch_height, patch_width)  #the U-net model
  File "./src/retinaNN_training.py", line 125, in get_unet
    model.compile(optimizer='sgd', loss=Tai_loss,metrics=['accuracy'])
NameError: global name 'Tai_loss' is not defined
